### PR TITLE
Rollout improved example converter

### PR DESCRIPTION
**Pull request by t0yv0**
Rolls out improved TF example converter.

### CODE REVIEW

**Comment by VenelinMartinov** [comment]
Some dropped examples here:

AlpineRepository is dropped because of terraform in the resource name - should we be renaming that?

DistributionPublicKey is dropped and I can't see why.

**Comment by t0yv0** [comment]
```{
  "ExampleName": "#/resources/artifactory:index/alpineRepository:AlpineRepository",
  "OriginalHCL": "resource \"artifactory_keypair\" \"some-keypairRSA\" {\n  pair_name         = \"some-keypair\"\n  pair_type         = \"RSA\"\n  alias             = \"foo-alias\"\n  private_key       = file(\"samples/rsa.priv\")\n  public_key        = file(\"samples/rsa.pub\")\n  lifecycle {\n    ignore_changes  = [\n      private_key,\n      passphrase,\n    ]\n  }\n}\n\nresource \"artifactory_local_alpine_repository\" \"terraform-local-test-alpine-repo-basic\" {\n  key                 = \"terraform-local-test-alpine-repo-basic\"\n  primary_keypair_ref = artifactory_keypair.some-keypairRSA.pair_name\n\n  depends_on          = [artifactory_keypair.some-keypairRSA]\n}\n",
  "ConversionResults": {
    "csharp": {
      "FailureSeverity": 2,
      "FailureInfo": "pcl.BindProgram failed: example.pp:4,23-39: unknown package 'std'; unknown package 'std', and 1 other diagnostic(s)",
      "Program": "",
      "TranslationCount": 1
    },
    "go": {
      "FailureSeverity": 2,
      "FailureInfo": "pcl.BindProgram failed: example.pp:4,23-39: unknown package 'std'; unknown package 'std', and 1 other diagnostic(s)",
      "Program": "",
      "TranslationCount": 1
    },
    "java": {
      "FailureSeverity": 2,
      "FailureInfo": "pcl.BindProgram failed: example.pp:4,23-39: unknown package 'std'; unknown package 'std', and 1 other diagnostic(s)",
      "Program": "",
      "TranslationCount": 1
    },
    "python": {
      "FailureSeverity": 2,
      "FailureInfo": "pcl.BindProgram failed: example.pp:4,23-39: unknown package 'std'; unknown package 'std', and 1 other diagnostic(s)",
      "Program": "",
      "TranslationCount": 1
    },
    "typescript": {
      "FailureSeverity": 2,
      "FailureInfo": "pcl.BindProgram failed: example.pp:4,23-39: unknown package 'std'; unknown package 'std', and 1 other diagnostic(s)",
      "Program": "",
      "TranslationCount": 1
    },
    "yaml": {
      "FailureSeverity": 2,
      "FailureInfo": "pcl.BindProgram failed: example.pp:4,23-39: unknown package 'std'; unknown package 'std', and 1 other diagnostic(s)",
      "Program": "",
      "TranslationCount": 1
    }
  }
}
```

**Comment by t0yv0** [comment]
I might need to add std package and rebuild.

**Comment by t0yv0** [comment]
Both examples are back.

**Pull request merged**
